<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TARge25Shop.ApplicationServices\TARge25_Shop.ApplicationServices.csproj" />
    <ProjectReference Include="..\TARge25_Shop.Core\TARge25_Shop.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\multipleFileUpload\" />
  </ItemGroup>

</Project>
